#include "nike_ntt.h"
#include "params.h"

typedef struct { unsigned n; uint16_t psi,omega,invpsi,invomega,invn; int inited; } ntt_ctx;
static ntt_ctx ctxs[2]={{1024,0,0,0,0,0,0},{2048,0,0,0,0,0,0}};
static ntt_ctx* getctx(unsigned n){ for(int i=0;i<2;i++) if(ctxs[i].n==n) return &ctxs[i]; return 0; }
static uint16_t powmod(uint16_t a, uint32_t e){ uint32_t r=1,b=a; while(e){ if(e&1) r=(r*b)%PARAM_Q; b=(b*b)%PARAM_Q; e>>=1;} return (uint16_t)r; }
static uint16_t invmod(uint16_t a){ return powmod(a, PARAM_Q-2); }
static void bitrev(uint16_t *a,unsigned n){ for(unsigned i=1,j=0;i<n;i++){ unsigned bit=n>>1; for(; j&bit; bit>>=1) j^=bit; j^=bit; if(i<j){ uint16_t t=a[i]; a[i]=a[j]; a[j]=t; } } }
int nike_ntt_init_n(unsigned n){ ntt_ctx*c=getctx(n); if(!c) return -1; if(c->inited) return 0; for(uint16_t cand=2;cand<PARAM_Q;cand++){ if(powmod(cand,n)==PARAM_Q-1 && powmod(cand,2*n)==1){ c->psi=cand; break; } } if(!c->psi) return -1; c->omega=powmod(c->psi,2); c->invpsi=invmod(c->psi); c->invomega=invmod(c->omega); c->invn=invmod((uint16_t)n); c->inited=1; return 0; }
uint16_t nike_ntt_psi_n(unsigned n){ ntt_ctx*c=getctx(n); if(!c) return 0; if(!c->inited) nike_ntt_init_n(n); return c->psi; }
void nike_cyclic_ntt_n(uint16_t *a,unsigned n){ ntt_ctx*c=getctx(n); if(!c||(!c->inited&&nike_ntt_init_n(n))) return; bitrev(a,n); for(unsigned len=2; len<=n; len<<=1){ uint16_t wlen=powmod(c->omega, n/len); for(unsigned i=0;i<n;i+=len){ uint16_t w=1; for(unsigned j=0;j<len/2;j++){ uint16_t u=a[i+j], v=(uint32_t)a[i+j+len/2]*w%PARAM_Q; uint16_t x=u+v; if(x>=PARAM_Q) x-=PARAM_Q; int32_t y=(int32_t)u-(int32_t)v; if(y<0) y+=PARAM_Q; a[i+j]=x; a[i+j+len/2]=(uint16_t)y; w=(uint32_t)w*wlen%PARAM_Q; } } } }
void nike_cyclic_intt_n(uint16_t *a,unsigned n){ ntt_ctx*c=getctx(n); if(!c||(!c->inited&&nike_ntt_init_n(n))) return; bitrev(a,n); for(unsigned len=2; len<=n; len<<=1){ uint16_t wlen=powmod(c->invomega, n/len); for(unsigned i=0;i<n;i+=len){ uint16_t w=1; for(unsigned j=0;j<len/2;j++){ uint16_t u=a[i+j], v=(uint32_t)a[i+j+len/2]*w%PARAM_Q; uint16_t x=u+v; if(x>=PARAM_Q) x-=PARAM_Q; int32_t y=(int32_t)u-(int32_t)v; if(y<0) y+=PARAM_Q; a[i+j]=x; a[i+j+len/2]=(uint16_t)y; w=(uint32_t)w*wlen%PARAM_Q; } } } for(unsigned i=0;i<n;i++) a[i]=(uint32_t)a[i]*c->invn%PARAM_Q; }
void nike_mul_negacyclic_ntt_n(uint16_t *out,const uint16_t *a,const uint16_t *b,unsigned n){ ntt_ctx*c=getctx(n); static uint16_t ta[NIKE_MAX_N],tb[NIKE_MAX_N]; if(!c||(!c->inited&&nike_ntt_init_n(n))) return; for(unsigned i=0;i<n;i++){ ta[i]=(uint32_t)a[i]*powmod(c->psi,i)%PARAM_Q; tb[i]=(uint32_t)b[i]*powmod(c->psi,i)%PARAM_Q; } nike_cyclic_ntt_n(ta,n); nike_cyclic_ntt_n(tb,n); for(unsigned i=0;i<n;i++) ta[i]=(uint32_t)ta[i]*tb[i]%PARAM_Q; nike_cyclic_intt_n(ta,n); for(unsigned i=0;i<n;i++) out[i]=(uint32_t)ta[i]*powmod(c->invpsi,i)%PARAM_Q; }
int nike_ntt_init(void){ return nike_ntt_init_n(1024);} uint16_t nike_ntt_psi(void){ return nike_ntt_psi_n(1024);} void nike_cyclic_ntt(uint16_t *a){ nike_cyclic_ntt_n(a,1024);} void nike_cyclic_intt(uint16_t *a){ nike_cyclic_intt_n(a,1024);} void nike_mul_negacyclic_ntt(poly*out,const poly*a,const poly*b){ nike_mul_negacyclic_ntt_n(out->coeffs,a->coeffs,b->coeffs,1024);} 
